Freight analysis
matsim-scenarios/matsim-leipzig pull request #26
Opened 2023-05-25 08:36 UTC by danielundgit

duplicated ExtractPersonEvents (called ExtractFreightEvents) to get freight or in general event type activities out from an event file

2023-05-25 08:48 UTC, simei94 requested changes
pls adapt your code such that it checks all the sonar cloud requirements

2023-05-25 12:27 UTC, GregorRyb commented
@simei94 I think not having a test for this analysis is ok...

2023-05-31 09:14 UTC, GregorRyb commented
Actual there is a bug you should fix before we can merge it. Also I would suggest that you just use the ActivityStartEventHandler for example, instead of all events and then filter for freight. Then you could clean up your code a bit more. If you need help let us know. Thanks!

2023-05-31 11:52 UTC, kainagel commented
@rakow : Könntest Du da bitte mal reinschauen?  Meine Intuition ist, dass wir `event.getAttributes()` von außen nicht verwenden sollten; stattessen `instanceof ...`, dann casten, dann typisierter Zugriff.  Man könnte versuchen, `getAttributes()` protected zu machen; wird nur an ganz wenigen Stellen verwendet, und die könnte man in die gleiche package moven.  (Leider gibt es core.events und api.core...events ... my (very old) fault.)

2025-04-29 12:23 UTC, closed without merging