make creation of DrtStops + intermodal TransitSchedule part of run class
matsim-scenarios/matsim-leipzig pull request #27
Opened 2023-05-31 09:25 UTC by simei94

2023-06-01 15:53 UTC, rakow requested changes

2023-06-01 15:53 UTC, rakow commented on src/main/java/org/matsim/run/prepare/PrepareTransitSchedule.java
> +	private static final Map<Id<TransitStopFacility>, TransitStopFacility> consideredStops = new HashMap<>();
Please don't make this static.

2023-06-01 15:53 UTC, rakow commented on src/main/java/org/matsim/run/prepare/PrepareTransitSchedule.java
> +	private static boolean railwaysOnly;
No static variables...

2023-08-03 17:56 UTC, simei94 commented
@GregorRyb this is done now, should we wait for CR before merging into v1.2 branch?

2023-08-21 15:31 UTC, GregorRyb approved these changes

2023-08-28 17:58 UTC, merged